-- General mappings
  require('plugins')
  require('keymappings')
  require('settings')
	require('colorscheme')

  -- Plugins
  require('nv-barbar')
  require('nv-colorizer')
  require('nv-comment')
  require('nv-compe')
  require('nv-dashboard')
  require('nv-galaxyline')
  require('nv-gitblame')
  require('nv-gitsigns')
  require('nv-lightbulb')
  require('nv-lspkind')
  require('nv-neogit')
  require('nv-nvimtree')
  require('nv-telescope')
  require('nv-vsnip')
  -- require('nv-blankline')
  -- require('nv-treesitter')

  -- LSP
  require('lsp')
  require('lsp.lua-ls')
  require('lsp.bash-ls')
  require('lsp.js-ts-ls')
  require('lsp.python-ls')
  require('lsp.json-ls')
  require('lsp.yaml-ls')
  require('lsp.vim-ls')
  require('lsp.graphql-ls')
  require('lsp.css-ls')
  require('lsp.docker-ls')
  require('lsp.html-ls')
  require('lsp.efm-general-ls')
  require('lsp.rust-ls')
  require('lsp.virtual_text')
  require('lsp.rust-analyzer-ls')
